export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const CHANGE_SUB_CATEGORY = 'CHANGE_SUB_CATEGORY';

export const REQUEST_SUBS_PENDING = 'REQUEST_SUBS_PENDING';
export const REQUEST_SUBS_SUCCESS = 'REQUEST_SUBS_SUCCESS';
export const REQUEST_SUBS_FAILED = 'REQUEST_SUBS_FAILED';